spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crud?characterEncoding=UTF-8
    username: crud
    password: Crud123!

  jpa:
    properties:
      hibernate:
        format_sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  redis:
    port: 6379
    host: localhost

logging:
  level:
    org.hibernate.SQL: debug